/* tb_gcr_read.v — unit testbench for the IWM (GCR) read path: 400K/800K.
 *
 * WHY THIS EXISTS (2026-08-05): mounting a raw 800K GCR image on hardware
 * gives "This disk is unreadable", and the driver posts -69 badCksmErr =
 * "addr mark checksum didn't check". The GCR ADDRESS field is generated by
 * floppy_track_encoder.v from track/sector/side/format with a checksum taken
 * over exactly those values, so the field is SELF-CONSISTENT by construction
 * — no image data is involved. A self-consistent field can therefore only
 * fail its checksum if the byte STREAM is damaged between the encoder and the
 * CPU. That is the IWM delivery path (floppy.v's byte-cell timer +
 * newByteReady, and swim.v's readDataLatch / readLatchClearTimer /
 * readDataArmDelay), which had no test coverage at all.
 *
 * WHAT IT DOES: drives the IWM soft switches the way the ROM does (enable
 * drive, select internal, park the phases on RDDATA0, q6=q7=0), then polls
 * the data register and captures every byte whose MSB is set — exactly the
 * ROM's "valid read" criterion. Prints the captured stream as hex for
 * offline decoding by scripts/gcr_census.py.
 *
 * THE EXPERIMENT: +pollgap=N inserts N extra 32 MHz clocks between polls, so
 * the same stream can be read at different CPU rates.
 *   pollgap small  = an unrealistically fast reader. Corruption here means
 *                    the encoder/delivery is broken on its own.
 *   pollgap ~40    = ~1.25 us per access, the LC's real E-paced VPA rate.
 * A stream that is clean fast and dirty slow is a delivery/latch timing bug,
 * not an encoder bug.
 *
 * TRACK/SIDE SWEEP (2026-08-05 pm, the "mounts but file content fails" hunt):
 *   +track=N  step the head to track N through the real drive-register
 *             protocol (DIRTN + N STEP strobes on the phase lines) before
 *             reading — this also exercises floppy.v's driveTrack counter.
 *   +side=N   park the phases on RDDATA1 (side 1) instead of RDDATA0.
 *   +ncap=N   capture N bytes (default 6000; use 14000 for a full 12-spt
 *             track cycle).
 * The image model is a full 819200-byte self-addressing pattern: 512-byte
 * block B holds [B.lo, B.hi, (B+j)&0xFF ...], so a decoded DATA field
 * identifies exactly which image offset the encoder actually fetched.
 * scripts/gcr_data_census.py decodes address AND data fields and verifies
 * each sector's payload against the offset the standard 800K GCR layout
 * demands — wrong-but-checksum-valid serving is exactly what it catches.
 *
 * Build + run (Verilator 5.x, from verilator/):
 *   verilator --binary -j 0 -Wno-fatal --timescale 1ns/1ps +define+SIMULATION \
 *     -I../rtl --Mdir /tmp/obj_gcr --top-module tb_gcr_read tb_gcr_read.v \
 *     ../rtl/swim.v ../rtl/floppy.v ../rtl/mfm_track_encoder.v \
 *     ../rtl/floppy_track_encoder.v
 *   /tmp/obj_gcr/Vtb_gcr_read +pollgap=40 > gcr_stream.txt
 *   python ../scripts/gcr_census.py gcr_stream.txt
 */

`timescale 1ns/1ps

module tb_gcr_read;

	reg clk = 0;
	always #15.625 clk = ~clk;          // 32 MHz

	reg [1:0] phase = 0;
	always @(posedge clk) phase <= phase + 1'b1;
	wire cep = (phase == 2'd0);
	wire cen = (phase == 2'd2);

	reg _reset = 0;

	// ---- CPU-side SWIM bus
	reg        selectSWIM = 0;
	reg        _cpuRW = 1;
	reg        _cpuUDS = 1;
	reg [15:0] dataIn = 0;
	reg [3:0]  cpuAddrRegHi = 0;
	reg        SEL = 0;          // VIA PA5 / HDSEL: 0 => RDDATA0 = side 0
	reg        driveSel = 1;     // internal drive select (IWM _enable term)
	wire [15:0] dataOut;

	// ---- disk image model. Full 800K so every track/side/zone is addressable.
	// Self-addressing pattern (see header): block number in bytes 0-1, then
	// (B+j)&0xFF — any mis-mapped fetch is identifiable from the payload.
	localparam IMG_BYTES = 819200;
	reg [7:0] img [0:IMG_BYTES-1];

	wire [21:0] dskReadAddrInt, dskReadAddrExt;
	reg         dskReadAckInt = 0;
	wire        dskReadAckExt = 1'b0;
	wire [7:0]  dskReadData = (dskReadAddrInt < IMG_BYTES) ? img[dskReadAddrInt] : 8'hE5;
	wire [6:0]  dbg_track;
	wire        dbg_side;
	// +ds=0 selects the SINGLE-sided 400K geometry (floppy_track_encoder's
	// `sides`=0 path, which nothing else exercises). Driven from an initial
	// plusarg before reset is released.
	reg         tb_ds = 1'b1;

	// Periodic fetch ack, mimicking addrController's extra bus slot (~2 us).
	integer ack_div = 0;
	always @(posedge clk) begin
		if (cen) begin
			ack_div <= ack_div + 1;
			if (ack_div >= 8) begin
				ack_div <= 0;
				dskReadAckInt <= 1'b1;
			end else
				dskReadAckInt <= 1'b0;
		end
	end

	swim dut (
		.clk(clk), .cep(cep), .cen(cen),
		._reset(_reset),
		.selectSWIM(selectSWIM),
		._cpuRW(_cpuRW),
		._cpuUDS(_cpuUDS),
		.dataIn(dataIn),
		.cpuAddrRegHi(cpuAddrRegHi),
		.SEL(SEL),
		.driveSel(driveSel),
		.dataOut(dataOut),
		.insertDisk(2'b01),      // internal drive: disk in
		.diskEject(),
		.diskSides({1'b0, tb_ds}),  // 1 = double-sided 800K, 0 = 400K (+ds=0)
		.diskMFM(2'b00),         // GCR disk -> IWM path
		.diskHD(2'b00),
		.diskMotor(), .diskAct(),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.dskReadData(dskReadData),
		.dbg_ism_flpe(),
		.dbg_flp_byte_cnt(), .dbg_flp_miss_cnt(), .dbg_flp_disk_data(),
		.dbg_flp_track(dbg_track), .dbg_flp_side(dbg_side), .dbg_flp_step_cnt(),
		.dbg_iwm_latch(), .dbg_flp_byte_stb(), .dbg_flp_raw(),
		.dbg_ism_state(),
		.dbg_flp_strb_cnt(), .dbg_flp_strb_en_cnt(), .dbg_flp_strb_last(),
		.dbg_flp_rej_step(), .dbg_flp_status(), .dbg_flp_gcr_addr(),
		.dbg_ism_verdict(), .dbg_ism_unrlatch(),
		.dbg_ism_scan(), .dbg_mfm_stall()
	);

	// ---- CPU access model. The SWIM sits in VPA space on the LC, so EVERY
	// register access is E-paced (~1.23 us at E = 812.5 kHz) — about 40
	// clocks at 32 MHz. The ROM's GCR poll loop (a6e1a0..a6e1b2) is:
	//     moveb %a5@,%a5@   ; VIA1 ORA (PA7 test)  <- one VPA access
	//     bmis  ...
	//     moveb %a4@,%d5    ; IWM data register    <- another VPA access
	//     dbf / bpls        ; loop while MSB clear
	// so the data register is re-read about every 2.5 us, and the CPU
	// latches the value at the END of its bus cycle.
	//   +acclen=N  clocks the access holds UDS low   (default 40 = 1.25 us)
	//   +pollgap=N clocks between accesses           (default 40 = the VIA read)
	integer pollgap = 0;
	integer acclen  = 10;
	integer req_track = 0;
	integer req_side  = 0;
	integer ncap_want = 6000;
	integer req_ds    = 1;

	task swim_wr(input [3:0] a, input [7:0] d);
	begin
		@(posedge clk);
		cpuAddrRegHi <= a; dataIn <= {8'h00, d}; _cpuRW <= 1'b0;
		selectSWIM <= 1'b1; _cpuUDS <= 1'b0;
		repeat (10) @(posedge clk);
		selectSWIM <= 1'b0; _cpuUDS <= 1'b1; _cpuRW <= 1'b1;
		repeat (10) @(posedge clk);
	end
	endtask

	task swim_rd(input [3:0] a, output [7:0] d);
	begin
		@(posedge clk);
		cpuAddrRegHi <= a; _cpuRW <= 1'b1;
		selectSWIM <= 1'b1; _cpuUDS <= 1'b0;
		repeat (acclen) @(posedge clk);
		d = dataOut[15:8];               // CPU latches at END of the bus cycle
		selectSWIM <= 1'b0; _cpuUDS <= 1'b1;
		repeat (4) @(posedge clk);
		if (pollgap > 0) repeat (pollgap) @(posedge clk);
	end
	endtask

	localparam NCAP_MAX = 20000;
	reg [7:0] cap [0:NCAP_MAX-1];
	integer   ncap = 0;

	// Drive-register write through the phase lines, the way the ROM does it:
	// {ca1,ca0,SEL} = register address, ca2 = data bit, committed on the
	// LSTRB falling edge (floppy.v lstrbEdge). SEL is a direct wire (VIA PA5),
	// not an IWM soft switch, so the caller sets it before this task.
	task drive_wr(input rca1, input rca0, input dat);
	begin
		swim_wr(rca1 ? 4'd3 : 4'd2, 8'h00);  // ca1
		swim_wr(rca0 ? 4'd1 : 4'd0, 8'h00);  // ca0
		swim_wr(dat  ? 4'd5 : 4'd4, 8'h00);  // ca2 = data value
		swim_wr(4'd7, 8'h00);                // LSTRB on
		swim_wr(4'd6, 8'h00);                // LSTRB off -> falling edge commits
		repeat (200) @(posedge clk);         // drive settle
	end
	endtask

	reg [7:0] v;
	integer   i, guard, blk;

	initial begin
		// self-addressing image: block number in bytes 0/1, then (B+j)&0xFF
		for (i = 0; i < IMG_BYTES; i = i + 1) begin
			blk = i >> 9;
			img[i] = ((i & 511) == 0) ? (blk & 255) :
			         ((i & 511) == 1) ? ((blk >> 8) & 255) :
			         ((blk + (i & 511)) & 255);
		end

		if (!$value$plusargs("pollgap=%d", pollgap)) pollgap = 0;
		if (!$value$plusargs("acclen=%d", acclen))  acclen  = 10;
		if (!$value$plusargs("track=%d", req_track)) req_track = 0;
		if (!$value$plusargs("side=%d", req_side))   req_side  = 0;
		if (!$value$plusargs("ncap=%d", ncap_want))  ncap_want = 6000;
		if (ncap_want > NCAP_MAX) ncap_want = NCAP_MAX;
		if ($value$plusargs("ds=%d", req_ds)) tb_ds = (req_ds != 0);

		_reset = 0;
		repeat (40) @(posedge clk);
		_reset = 1;
		repeat (40) @(posedge clk);

		// ---- IWM setup, exactly the soft-switch order the ROM uses ----
		swim_wr(4'd10, 8'h00);   // select INTERNAL drive (ext select off)
		swim_wr(4'd9,  8'h00);   // disk enable ON  (motor)
		swim_wr(4'd14, 8'h00);   // q7 = 0
		swim_wr(4'd12, 8'h00);   // q6 = 0  -> read data register

		// ---- seek: DIRTN=0 (toward 79), then req_track STEP strobes ----
		SEL = 1'b0;              // register addressing needs SEL low
		if (req_track > 0) begin
			drive_wr(1'b0, 1'b0, 1'b0);            // DIRTN = 0: step inward
			for (i = 0; i < req_track; i = i + 1)
				drive_wr(1'b0, 1'b1, 1'b0);        // STEP (write 0 = do step)
		end

		// park the phases on RDDATA0/1 = {ca2,ca1,ca0,SEL} = 100,side
		swim_wr(4'd2,  8'h00);   // ca1 = 0
		swim_wr(4'd0,  8'h00);   // ca0 = 0
		SEL = req_side[0];       // head select BEFORE ca2 raises the read addr
		swim_wr(4'd5,  8'h00);   // ca2 = 1

		// the post-enable squelch in swim.v is ~126 us; wait it out
		repeat (200000) @(posedge clk);

		$display("# tb_gcr_read seek done: driveTrack=%0d driveSide=%0d (want %0d/%0d)",
		         dbg_track, dbg_side, req_track, req_side);

		// ---- poll the data register; MSB set = a valid byte (ROM's rule) ----
		guard = 0;
		while (ncap < ncap_want && guard < 40000000) begin
			swim_rd(4'd12, v);
			if (v[7]) begin
				cap[ncap] = v;
				ncap = ncap + 1;
			end
			guard = guard + 1;
		end

		$display("# tb_gcr_read pollgap=%0d acclen=%0d track=%0d side=%0d captured=%0d",
		         pollgap, acclen, req_track, req_side, ncap);
		for (i = 0; i < ncap; i = i + 1)
			$write("%02x%s", cap[i], ((i % 16) == 15) ? "\n" : " ");
		$write("\n");
		$finish;
	end

endmodule
